### ISSUE TITLE
Create router component

### ISSUE THREAD

**Issue by anlesk** [Code-Rush-Experement/decompositor#2]
It should handle route changes and post message about it

**Comment by chaos-adept** [comment]
fake router has been added - https://github.com/Code-Rush-Experement/decompositor/commit/9fd42d59b679c07e92862b15b79a6b9771cf1501

**Comment by chaos-adept** [comment]
so far we have raised question, sould be have separated space for route events, like `router/home`, another option is to handle custom event and make routing (we have it in https://github.com/Code-Rush-Experement/decompositor/commit/3ea452951b3876dd56d6c41bddfbfe7544bb2e05 , it seems to be incorrect solution)

**Comment by chaos-adept** [comment]
@anlesk it seems that we need to start using NPM for making a core, i need to use some virtual dom library for make tranisitions between routes in the SPA way,

actually i could do it by bicycle, but it seems to be too big

**Comment by anlesk** [comment]
Totally makes sense for me. Closing this task due to it's completion.
